### ISSUE TITLE
[ENHANCEMENT] Modif/feat detected-clans

### ISSUE THREAD

**Issue by BadySkull** [Glassait/FOLD_Bot#239]
Ajouter une commande pour ignorer des clans du detected-clans. Exemple : les clans inter déjà sortis les mois précédents ?

===

Revoir également le fonctionnement autour du "detected-clans" pour avoir cette logique : 

- joueur qui passe dans le bot recrutement quotidien
- stockage du joueur
- 1er juillet - 0h00 : preparation de la commande detected-clan
        > Parcours tous les joueurs stockés :
                -> Si joueur dans un clan & que le clan n'est pas observé jusque là, stockage du clan pour le retour de la cmd
                -> Si joueur pas dans un clan ou clan déjà observé, on skip.
        > Mise "en attente" de la liste jusqu'à l'appel detected-clan des clans stockés sur la derniere iteration
        > Drop de la liste de tous les joueurs stockés 

- 1er juillet - 10h00 : passage du bot recrutement quotidien & début alimentation d'une nouvelle liste de joueurs
- Appel du detected-clan (ex: 2 juillet - 0h10) : retourne la liste des clans stockée qui avait été mise en attente. Puis drop la liste en prévision de la prochaine préparation

**Comment by Glassait** [comment]
TODO : 
- [ ] Add filter on language speak by the clan
- [ ] Remove at any case the leaving player
